# Streamlit Cloud Secrets Configuration
# Copy your actual values from your .env file here

SUPABASE_URL = "https://eksrinfygfabsezbaspq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrc3JpbmZ5Z2ZhYnNlemJhc3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDMzMzAsImV4cCI6MjA2NzA3OTMzMH0.uwd-Q0bljbOAmg3CB1foaEgTuGPdA1Wi1NeCX4oDZQQ"
SUPABASE_SERVICE_ROLE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrc3JpbmZ5Z2ZhYnNlemJhc3BxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTUwMzMzMCwiZXhwIjoyMDY3MDc5MzMwfQ.F_rvUG2DocksNmcO487IffeH6QyqSzyI1b_847yrqQ4" 