# Streamlit Cloud Secrets Configuration
# Copy your actual values from your .env file here

SUPABASE_URL = "your-supabase-url-here"
SUPABASE_ANON_KEY = "your-supabase-anon-key-here"
SUPABASE_SERVICE_ROLE = "your-supabase-service-role-key-here" 